project_id = "trevewovdgsxhatsytlw"

[functions.neo-chat]
verify_jwt = false

[functions.threat-analysis]
verify_jwt = false

[functions.intel-aggregator]
verify_jwt = false

[functions.code-assistant]
verify_jwt = false