// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trevewovdgsxhatsytlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZXZld292ZGdzeGhhdHN5dGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzIwNjEsImV4cCI6MjA2NTg0ODA2MX0.OGw0Ibfyp6MR0J-1Yb97HlpCe_JO1cSOp27Y8Ea_WmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});